<a href="https://colab.research.google.com/github/ironcevic/basic_stats/blob/main/Hubbard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Good morning! Before we begin, let's recall some maths:

$|a\rangle$ is a basis state.

$|b\rangle$ is another one.

Basis states live in a Hilbert space.

$⟨a|b⟩$ is the overlap (inner product) between $|a⟩$ and $|b⟩$. If we define our states to be orthonormal, we have:

$⟨a|b⟩$ = 0

$⟨a|a⟩$ = $⟨b|b⟩$ = 1

**Problem 1.** Given $|\psi⟩$ = $\frac{|a\rangle + |b\rangle}{\sqrt{2}}$, compute $⟨a|\psi⟩$.

We can move from one basis, $|a⟩$ and $|b⟩$, to another, e.g., $|+⟩$ and $|-⟩$, by using the outer product:

$|a⟩⟨a| = 1$

**Problem 2.** Given $|+⟩ = \frac{|a\rangle + |b\rangle}{\sqrt{2}}$ and $|-\rangle = \frac{|a\rangle - |b\rangle}{\sqrt{2}}$, write $|a⟩$ and $|b⟩$ in terms of $|+⟩$ and $|-⟩$. Both $|a⟩$ and $|b⟩$, and $|+⟩$ and $|-⟩$ are orthonormal.

Hint: $|a⟩ = |+⟩⟨+|a⟩ + |-⟩⟨-|a⟩$.

Now we can start exploring the Hückel model. This is the simplest quantum-chemical model that one can build. It includes electron delocalisation, but not electron-electron repulsion nor spin. In second quantisation, the Hückel Hamiltonian is given by:

$H = - \sum_{i,j\neq i} t_{ij} \ c_i^\dagger c_j + \sum_i n_i \ \epsilon_i$

where

$t_{ij}$ is the coupling between sites $i$ and $j$,

$c_i^\dagger$ creates an electron at site $i$,

$n_i = c_i^\dagger c_i$ counts the number of electrons at site $i$,

$c_j$ destroys an electron at site $j$, and

$\epsilon_i$ is the self-energy of site $i$.

The Hückel Hamiltonian is solved in a Hilbert space defined by one electron and $i$ sites. This is a very small Hilbert space, which we like.

**Problem 3.** Using the code below, solve the Hückel Hamiltonian for a ring of four sites with nearest-neighbour coupling only and $\epsilon_i = 0 $. This may be viewed as a model of the $\mathrm{\pi_z}$-electrons in cyclobutadiene. Plot the MOs. Then, explore the effect of bond length alternation.

Hint: the Hückel matrix elements are given by $H_{ij} = ⟨a_i|H|a_j⟩$.

The basis states are: $|1000⟩, |0100⟩, |0010⟩, |0001⟩$. The $t$ term  moves an electron to the next site, so:

$⟨1000|H|0100⟩ = -t$, as the electron moves by one site, and

$⟨1000|H|0010⟩ = 0$, as an electron moves by two sites.



In [1]:
# Here is module that will give us symmetry-adapted MOs. Also some imports.
!pip install qutip
import numpy as np
from qutip import *

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.1/33.1 MB 35.1 MB/s eta 0:00:00


In [4]:
t = -1 # we don't really care about the value of t
d = 0.1
# Here is the matrix, now fill it out!
H = np.array([
#  1  2  3  4 site number
  [-2, t+d, 0, t-d], # 1
  [t+d, -2, t-d, 0], # 2
  [0, t-d, -2, t+d], # 3
  [t-d, 0, t+d, -2]  # 4
])
"""
This below is just Qutip stuff.
We could use np.eigh(H) instead,
but Qutip plays nice with symmetry.
"""

Q = Qobj(H)
MO_energies, MO_coefficients = Q.eigenstates()
print("MO energies are:")
print(np.round(np.real(MO_energies), 2))
print("The MOs are:")
for MO in range(len(MO_coefficients)):
    print(f"MO number {MO+1}:")
    print(np.round(np.real(MO_coefficients[MO].full()), 2))

MO energies are:
[-4.  -2.2 -1.8  0. ]
The MOs are:
MO number 1:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
MO number 2:
[[ 0.5]
 [-0.5]
 [-0.5]
 [ 0.5]]
MO number 3:
[[-0.5]
 [-0.5]
 [ 0.5]
 [ 0.5]]
MO number 4:
[[ 0.5]
 [-0.5]
 [ 0.5]
 [-0.5]]


**Problem 4.** Compare the IP (HOMO energy) of benzene and silabenzene, $\mathrm{C_5SiH_6}$.

In [8]:
t = -1 # we still don't care about the value of t
# Here is a 6x6 matrix
H_benzene = np.array([
#  1  2  3  4  5  6  site number
  [0, t, 0, 0, 0, t], # 1
  [t, 0, t, 0, 0, 0], # 2
  [0, t, 0, t, 0, 0], # 3
  [0, 0, t, 0, t, 0], # 4
  [0, 0, 0, t, 0, t], # 5
  [t, 0, 0, 0, t, 0], # 6
])

H_silabenzene = np.array([
#  1  2  3  4  5  6  site number
  [1, t, 0, 0, 0, t], # 1
  [t, 0, t, 0, 0, 0], # 2
  [0, t, 0, t, 0, 0], # 3
  [0, 0, t, 0, t, 0], # 4
  [0, 0, 0, t, 0, t], # 5
  [t, 0, 0, 0, t, 0], # 6
])
"""
This below is just Qutip stuff.
We could use np.eigh(H) instead,
but Qutip plays nice with symmetry.
"""
# choose your molecule
# H = H_benzene
H = H_silabenzene

Q = Qobj(H)
MO_energies, MO_coefficients = Q.eigenstates()
print("MO energies are:")
print(np.round(np.real(MO_energies), 2))
print("The MOs are:")
for MO in range(len(MO_coefficients)):
    print(f"MO {MO+1} composition:")
    print(np.round(np.real(MO_coefficients[MO].full()), 2))

MO energies are:
[-1.89 -1.   -0.7   1.    1.32  2.28]
The MOs are:
MO 1 composition:
[[-0.26]
 [-0.38]
 [-0.45]
 [-0.48]
 [-0.45]
 [-0.38]]
MO 2 composition:
[[ 0. ]
 [-0.5]
 [-0.5]
 [ 0. ]
 [ 0.5]
 [ 0.5]]
MO 3 composition:
[[ 0.5 ]
 [ 0.42]
 [-0.2 ]
 [-0.56]
 [-0.2 ]
 [ 0.42]]
MO 4 composition:
[[ 0. ]
 [-0.5]
 [ 0.5]
 [ 0. ]
 [-0.5]
 [ 0.5]]
MO 5 composition:
[[ 0.52]
 [-0.08]
 [-0.41]
 [ 0.62]
 [-0.41]
 [-0.08]]
MO 6 composition:
[[ 0.65]
 [-0.41]
 [ 0.29]
 [-0.26]
 [ 0.29]
 [-0.41]]


This is all fine and dandy, but electron–electron interactions are still missing. In the Hückel model, the MOs are fixed and don’t respond to occupancy, which limits it's  quantitative accuracy, but still makes it qualitatively useful.

The Hubbard model is a minimal improvement on top of Hückel: it keeps the same one‑electron hopping but adds an on‑site interaction. In its simplest form,

$H = - \sum_{ij \neq i,s} t_{ij} \ c_{i,s}^\dagger c_{j,s} + \sum_{i,s} n_{i,s} \ \epsilon_i + \sum_i U_i \ n_{i,\uparrow} n_{i, \downarrow} $

where the sums now include spin $s\in\{\uparrow,\downarrow\}$.

A few notes: one, the $U$ term only shifts some diagonal matrix elements, but this subtle change can radically change the ground state. Two, only opposite-spin electrons can occupy the same orbital, so $U$ connects spin and Coulombic repulsion! Three, $U$ can be negative (attractive), for example in superconductivity, demonstrating the ubiquity of the Hubbard model in nature.

The key complication is that electron number now matters. We can’t stay in a one‑electron basis and we must work in the many‑electron basis instead. The size of this basis grows exponentially with the size of the system. Let’s look at a few simple examples.

**Problem 5.** Using the code below, construct a Hubbard Hamiltonian of a dimer with two sites and two electrons. This could represent $\mathrm{H}_2$, the $\mathrm{\pi}$-electrons in $\mathrm{C_2H_2}$ (small $U/t$), or two weakly interacting radicals (large $U/t$). Assume $\epsilon_1 = \epsilon_2 = 0$.

**(a)** Identify the electronic states and write them in terms of the basis.

**(b)** Test $U/t = 0.1$ to $10$ and/or $\epsilon_1 \neq \epsilon_2$.  How does the state composition change?

**(c)** Under what conditions can triplet become the ground state? (This is hard.)

In [17]:
U = 100
t = -1
# Hubbard model, 2 sites and 2 electrons
H = np.array([
# uu ud du 20 02 dd
  [0, 0, 0, 0, 0, 0], # uu
  [0, 0, 0, t, t, 0], # ud
  [0, 0, 0, t, t, 0], # du
  [0, t, t, U, 0, 0], # 20
  [0, t, t, 0, U, 0], # 02
  [0, 0, 0, 0, 0, 0], # dd
])

Q = Qobj(H)
state_energies, state_coefficients = Q.eigenstates()
print("State energies are:")
print(np.round(np.real(state_energies), 2))
print("The states are:")
for state in range(len(state_coefficients)):
    print(f"State {state+1} composition:")
    print(np.round(np.real(state_coefficients[state].full()), 2))


State energies are:
[-4.0000e-02 -0.0000e+00  0.0000e+00  0.0000e+00  1.0000e+02  1.0004e+02]
The MOs are:
State 1 composition:
[[0.  ]
 [0.71]
 [0.71]
 [0.01]
 [0.01]
 [0.  ]]
State 2 composition:
[[ 0.  ]
 [ 0.71]
 [-0.71]
 [ 0.  ]
 [ 0.  ]
 [ 0.  ]]
State 3 composition:
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
State 4 composition:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
State 5 composition:
[[ 0.  ]
 [ 0.  ]
 [ 0.  ]
 [-0.71]
 [ 0.71]
 [ 0.  ]]
State 6 composition:
[[ 0.  ]
 [-0.01]
 [-0.01]
 [ 0.71]
 [ 0.71]
 [ 0.  ]]


**Problem 6.** Let us now look at a system with three electrons in three orbitals, focussing on the $m_\mathrm{s} = 1/2$ sector.

In [ ]:
U = 1
t = -1
# Hubbard model, 3 sites and 3 electrons
H = np.array([
# uud udu duu 2u0 20u u20 02u u02 0u2
 [ 0 , 0 , 0 , 0 , 0 , t , 0 , t , 0 ], # uud
 [ 0 , 0 , 0 , 0 , t , t , t , t , 0 ], # udu
 [ 0 , 0 , 0 , 0 , t , 0 , t , 0 , 0 ], # duu
 [ 0 , 0 , 0 , U , t , t , 0 , 0 , 0 ], # 2u0
 [ 0 , t , t , t , U , 0 , 0 , 0 , 0 ], # 20u
 [ t , t , 0 , t , 0 , U , 0 , 0 , 0 ], # u20
 [ 0 , t , t , 0 , 0 , 0 , U , 0 , t ], # 02u
 [ t , t , 0 , 0 , 0 , 0 , 0 , U , t ], # u02
 [ 0 , 0 , 0 , 0 , 0 , 0 , t , t , U ]  # 0u2
])

Q = Qobj(H)
state_energies, eigenstates = Q.eigenstates()
print("State energies are:")
print(np.round(np.real(state_energies), 2))
print("The MOs are:")
for state in range(len(eigenstates)):
    print(f"State {state+1} composition:")
    print(np.round(np.real(eigenstates[state].full()), 2))


**(a)** Using the code below, evaluate the spin density of the ground state.

Hint: The spin density at site $i$ is given by

$\rho_i^{\text{spin}} = \langle\psi | (n_{i,\uparrow} - n_{i,\downarrow}) | \psi \rangle$.

It might be useful to expand the wavefunction in terms of basis states $k$ with contributions $c_k$ and work this out algebraically first.

In [ ]:
# Here is the spin density of the basis states.
# Spin_densities[k] gives the spin density of basis state k.
spin_densities = np.array([
  [1, 1, -1],    # uud: up at 0,1 and down at 2
  [1, -1, 1],    # udu: up at 0,2 and down at 1
  [-1, 1, 1],    # duu: up at 1,2 and down at 0
  [0, 1, 0],     # 2u0: doubly occ at 0, up at 1, empty at 2
  [0, 0, 1],     # 20u: doubly occ at 0, empty at 1, up at 2
  [1, 0, 0],     # u20: up at 0, doubly occ at 1, empty at 2
  [0, 0, 1],     # 02u: empty at 0, doubly occ at 1, up at 2
  [1, 0, 0],     # u02: up at 0, empty at 1, doubly occ at 2
  [0, 1, 0]      # 0u2: empty at 0, up at 1, doubly occ at 2
])

# The next line selects the ground electronic state.
state_number = 0
spin_density = np.array([0.0, 0.0, 0.0])
for basis_state in range(len(eigenstates)): # sum over basis states
    c_k = np.real(eigenstates[state_number].full()[basis_state])
    # spin_density += this is where you write the solution

print("The spin density is:")
print(np.round(spin_density, 2))
print("The total spin density is:")
print(np.round(np.sum(spin_density), 2))


**(b)** Using the code below, compute the energy per electron and the vertical detachment energy of the 3-electron 3-site chain. Then transform the chains into rings. What has changed?

In [ ]:
U = 1
t = -1

# Hubbard model, 3 sites and 3 electrons
H_0 = np.array([
# uud udu duu 2u0 20u u20 02u u02 0u2
 [ 0 , 0 , 0 , 0 , 0 , t , 0 , t , 0 ], # uud
 [ 0 , 0 , 0 , 0 , t , t , t , t , 0 ], # udu
 [ 0 , 0 , 0 , 0 , t , 0 , t , 0 , 0 ], # duu
 [ 0 , 0 , 0 , U , t , t , 0 , 0 , 0 ], # 2u0
 [ 0 , t , t , t , U , 0 , 0 , 0 , 0 ], # 20u
 [ t , t , 0 , t , 0 , U , 0 , 0 , 0 ], # u20
 [ 0 , t , t , 0 , 0 , 0 , U , 0 , t ], # 02u
 [ t , t , 0 , 0 , 0 , 0 , 0 , U , t ], # u02
 [ 0 , 0 , 0 , 0 , 0 , 0 , t , t , U ]  # 0u2
])

# Hubbard model, 3 sites and 2 electrons
H_1 = np.array([
# ud0 u0d 0ud du0 d0u 0du 200 020 002
 [ 0 , t , 0 , 0 , 0 , 0 , t , t , 0 ], # ud0
 [ t , 0 , t , 0 , 0 , 0 , 0 , 0 , 0 ], # u0d
 [ 0 , t , 0 , 0 , 0 , 0 , 0 , t , t ], # 0ud
 [ 0 , 0 , 0 , 0 , t , 0 , t , t , 0 ], # du0
 [ 0 , 0 , 0 , t , 0 , t , 0 , 0 , 0 ], # d0u
 [ 0 , 0 , 0 , 0 , t , 0 , 0 , t , t ], # 0du
 [ t , 0 , 0 , t , 0 , 0 , U , 0 , 0 ], # 200
 [ t , 0 , t , t , 0 , t , 0 , U , 0 ], # 020
 [ 0 , 0 , t , 0 , 0 , t , 0 , 0 , U ]  # 002
])

def diagonalise(H, state_number=0):
    """
    Diagonalises a Hamiltonian.
    input:
    - Hamiltonian matrix (numpy array)
    - chosen state number (integer)
    output:
    - energies of all states (numpy array)
    - coefficients of the chosen state c_k (numpy array)
    """
    Q = Qobj(H)
    energies,  eigenstates = Q.eigenstates()
    c_k = []
    for basis_state in range(len(eigenstates)): # write over basis states
        c_k.append(np.real(eigenstates[state_number].full()[basis_state]))
    c_k = np.array(c_k)
    return energies, c_k

E_0, c_k_0 = diagonalise(H_0)
E_1, c_k_1 = diagonalise(H_1)
